#
###################################
# Site wide configuration
####################################
#
title:       "Jonathan Bijos"
description: "Curiosidades e experiências de programação"
url:         #"quaggie.github.io"

#
###################################
# Jekyll configuration
####################################
#
timezone:          Americas/São Paulo
markdown:          kramdown
syntax:            pygments
excerpt_separator: <!--more-->
permalink:         /:title

# kramdown:
#   auto_ids:       true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   enable_coderay: false


###################################
# Site Owner configuration
####################################
#
owner:
  name: Jonathan Bijos
  avatar: avatar.jpg
  job: "Desenvolvedor Javascript & Mobile"
  bio: "Curiosidades e experiências de programação"
  email: jonathanpbijos@gmail.com
  disqus-shortname: jonathanbijos
  twitter: BijosJonathan
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Quaggie
  stackoverflow: #123456/username
  linkedin: jonathanbijos
  xing: #username
  instagram: JonathanBijos
  lastfm: #username
  tumblr: #username
  pinterest: jonathanbijos
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
