#
###################################
# Site wide configuration
####################################
#
title:       "Jonathan Bijos"
description: "Curiosidades e experiências de programação"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Americas/São Paulo
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jonathan Bijos
  avatar: avatar.jpg
  job: "Desenvolvedor Javascript & Mobile"
  bio: "Bla bla bla bla bla bla bla bla bla bla"
  email: jonathanpbijos@gmail.com
  disqus-shortname:
  twitter: BijosJonathan
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Quaggie
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jonathanbijos
  xing: #username
  instagram: JonathanBijos
  lastfm: #username
  tumblr: #username
  pinterest: jonathanbijos
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
